### ISSUE TITLE
縦書き部分に text-combine-upright が使えないか検討

### ISSUE THREAD

**Issue by yomotsu** [pxgrid/codegrid-ui#12]
text-combine-upright で縦中横ができる
https://developer.mozilla.org/ja/docs/Web/CSS/text-combine-upright

Chrome, IE11 で現在対応
Fx41 では縦書きはサポートされたものの、未対応

**Comment by yomotsu** [comment]
たぶん今は使えない

**Comment by myakura** [comment]
Firefox 48でサポートされたので、ブラウザのサポートだけを見ると使えるようになりました。
ただ`digits`はTrident/EdgeHTML以外でサポートされてないので、縦中横にしたい箇所は明示的に`span`で包むなどしないといけないのは代わりありません。
