### ISSUE TITLE
クレジットカードのロゴを更新する

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#123]
Visa, Masterは変わって久しいし、Amexも最近変わったのでそろそろ変えたいなと。

**Comment by myakura** [comment]
これかなあ。

* Visa: https://www.visaeurope.com/receiving-payments/pos_branding
* MasterCard: https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html
* Amex: https://merchant-supplies.americanexpress.com/?locale=en_GB&inav=gb_business_merch_customer_logo#/catalog/producttype/digitalsigns
* JCB: https://www.jcb.co.jp/merchant/support/logo/jcb/download.html
* Diners: https://www.dinersclub.com/about-us/press/media-kit

ちょっとガイドラインも見てみる。

**Comment by myakura** [comment]
あ、あとPAY.JPではDiscoverも使えるらしい。
追加してもいいが…日本国内で発行できないからなあ。

**Comment by myakura** [comment]
こんな感じかな。

![cg-card-logo](https://user-images.githubusercontent.com/413984/42002693-20149eca-7aa3-11e8-97e5-9b1820462a23.png)

**Comment by kyosuke** [comment]
よさそう。なんか新しい感ある。

**Comment by myakura** [comment]
よくよく見たらuiにはファイルが追加されておらず、codegridのサイト・アプリそれぞれでやっていました。こちらはクローズして移動します。
