### ISSUE TITLE
Chromeで印刷（プレビュー）時に見出しなどの文字が消える

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#127]
![screen shot 2018-07-03 at 18 01 19](https://user-images.githubusercontent.com/413984/42210099-4e82f7b0-7eeb-11e8-98be-1af1d5980271.png)

特定のフォントファミリーを指定する場合に起こる感じ。もう少し細かくしらべる。

**Comment by soto3** [comment]
バージョン: 67.0.3396.99（Official Build） （64 ビット）

<img width="540" alt="2018-07-05 11 06 15" src="https://user-images.githubusercontent.com/746758/42299001-bd9dd986-8043-11e8-9648-dc9a188f9531.png">

こういう抜け方はけっこうつらいです。抜けているのは「最小値」「最大値」の2バイト文字です。

**Comment by myakura** [comment]
むー、コードの抜けもあるのですね…

**Comment by myakura** [comment]
ヘッダについては、Kleeから游明朝までを消すと復活したが…

**Comment by myakura** [comment]
消えている箇所と、使われているフォント：

* 記事ヘッダのシリーズ名と記事タイトル ― Palatino, Klee
* 見出し（h2） ― Palatino, Klee
* コードブロック ― Monaco, Osaka

いずれも日本語。

Kleeを消すとYuMinchoで解決されるのだけど、それでも消える。
YuMinchoを消すとHiragino Mincho ProNになるが、それでも消える。
更にそれを消すとHiragino Mincho Proになる。そしたら出た！

というわけで見出しについてはKleeからヒラギノ明朝Pro Nまで消す、もしくはserifだけにする。

問題はコードの日本語。コードについて日本語は何も指定してないのでデフォルトのOsakaが使われているのだが、代替となる等幅日本語フォントがたしかmacOSにない（気がする）。
印刷なのでヒラギノとかにしてもよさそうだが、アスキーアート勢がいるとつらそう。

**Comment by myakura** [comment]
> 印刷なのでヒラギノとかにしてもよさそうだが、アスキーアート勢がいるとつらそう。

まあそれでもそれはスクリーンで確認してもらうとして、とりあえずヒラギノ書いとくか。
