### ISSUE TITLE
その他色々

### ISSUE THREAD

**Issue by yomotsu** [pxgrid/codegrid-ui#15]
https://github.com/pxgrid/codegrid-app/pull/416#issuecomment-151378427

- [ ] 404.jade (デザインなし)
- [x] articles.jade (indexに統合？)
- [x] contact.jade
- [x] example.jade (メルマガサンプル: デザインなし)
- [x] faq.jade
- [x] index.jade
- [x] organization.jade
- [x] payment.jade
- [x] privacy.jade
- [x] なくなるregistration.jade (購読方法: デザインなし (要appの実際の画面キャプチャ))
- [x] なくなるresign.jade (退会方法: デザインなし (要appの実際の画面キャプチャ))
- [x] sample.jade (不要)
- [x] terms.jade
- [x] tokutei.jade

**Comment by leader22** [comment]
@yomotsu このIssueはもう〆てOKなやつです・・よね？

**Comment by yomotsu** [comment]
よさそうですね..close
