### ISSUE TITLE
記事詳細画面の購読開始導線とシェアボタンのHTML、CSS

### ISSUE THREAD

**Issue by ykhs** [pxgrid/codegrid-ui#26]
@yomotsu 

非ログイン・未購読時、の記事詳細画面で出る画面と、シェアボタン周りのHTML、CSSってもうどこかにありますか？ なかったらくださいー。

デザインはここでいただいてると思います。
https://pxgrid.slack.com/archives/codegrid-design/p1447823809000021

**いまの非ログイン・未購読時 記事詳細画面**

![local mmo codegrid 2015-12-04 19-10-10](https://cloud.githubusercontent.com/assets/203110/11587134/aa7d9c54-9aba-11e5-8689-a4cf127842f2.png)

**いまのシェアボタン**

![local mmo codegrid 2015-12-04 19-12-41](https://cloud.githubusercontent.com/assets/203110/11587185/03f00218-9abb-11e5-9099-8f8a47583fcf.png)

**Comment by yomotsu** [comment]
未ログイン時の誘導は、こんな感じで

body直下、<div class="CG2-articleHeader">のブロックの次に以下を
```
<div class="CG2-narrowLayout">
  <div class="CG2-narrowLayout__main">

    <div class="CG2-articleBeforeLogin">
      <div class="CG2-articleBeforeLogin__lead">この記事を読むには<br>購読の手続きが必要です</div>
      <div class="CG2-articleBeforeLogin__sub">CodeGridは月額800円（税抜き）、<br class="CG2--disableLargeScreen CG2--disableMiddleScreen">PayPal払いなら30日無料</div>
      <div class="CG2-articleBeforeLogin__buttonContainer">
        <ul>
          <li><a class="CG2-button CG2-button--primary" href="#">購読の手続きへ</a></li>
          <li><a class="CG2-button" href="#">購読済みの方はログイン</a></li>
        </ul>
      </div>
    </div>

  </div>
</div>
```

シェアするボタンはこんな感じで（「お気に入りに登録」は必要に応じて削除してください）
```
<div class="CG2-articleUtil">
  <ul>
    <li><button class="CG2-button CG2-button--action" data-socialitems-append><span class="CG2-icon-facebook"></span><span class="CG2-icon-twitter"></span> シェアする</button></li>
    <li><button class="CG2-button CG2-button--action"><span class="CG2-icon-star"></span> お気に入りに登録</button></li>
  </ul>
  <div class="CG2-articleUtil__socialItems"></div>
  <script src="https://platform.twitter.com/widgets.js" async></script>
</div>
```

**Comment by yomotsu** [comment]
ping @ykhs

**Comment by ykhs** [comment]
@yomotsu 

すみません、未購読時の状態でボタンが横に2つ並べられないかもです。

![local mmo codegrid 2015-12-11 16-10-21](https://cloud.githubusercontent.com/assets/203110/11737963/c5bed7c8-a021-11e5-884d-9db8c4b79c31.png)

**Comment by ykhs** [comment]
シェアボタンの方はOKです

**Comment by yomotsu** [comment]
@ykhs 

文字サイズを下げて横に並ぶようにしました！

https://github.com/pxgrid/codegrid-ui/commit/38f515797a108ce545a35f56cb7064001b513343

**Comment by ykhs** [comment]
@yomotsu 

ありがとうございますー。直りました。
