### ISSUE TITLE
未読にするボタンのdisable

### ISSUE THREAD

**Issue by ykhs** [pxgrid/codegrid-ui#27]
@yomotsu 

記事詳細画面で「未読にする」を押したときに`[disabled]`が付きますが、見た目は特に変わらないので、なにかスタイルがあった方が良さそうです。

TWOTONさんにデザインからいただいた方が良いですかね？

![local mmo codegrid 2015-12-04 20-12-33](https://cloud.githubusercontent.com/assets/203110/11588401/84638f98-9ac3-11e5-8091-c4ece2edd818.png)

**Comment by yomotsu** [comment]
@ykhs 

http://ui.codegrid.net/styleguide/category/Nav-items/index.html#button

のdisabledを参考にしてください、単純にaやbuttonタグにCG2-button--disabledを追加していただければOKです

CG2-button--primaryなどのバリエーション違いでもそのまま追加するだけです

例
```
<a class="CG2-button CG2-button--disabled" href="#">button</a>
```
```
<a class="CG2-button CG2-button--primary CG2-button--disabled" href="#">primary button</a>
```

**Comment by ykhs** [comment]
@yomotsu 

ありがとうございますー。
