### ISSUE TITLE
導線なしフッター

### ISSUE THREAD

**Issue by ykhs** [pxgrid/codegrid-ui#28]
@yomotsu 

http://ui.codegrid.net/styleguide/category/Templates/index.html#Page%20Header
こちらに導線なしヘッダーがありますが、導線なしフッターってありますか？
いつだったかの会話ではあるって聞いてたような気がしたので。

**Comment by yomotsu** [comment]
これでお願いします！

```
<footer class="CG2-pageFooter CG2-pageFooter--simple">
  <div class="CG2-pageFooter__inner">
    <div class="CG2-pageFooter__legalNav">
      <div class="CG2-pageFooter__company">運営会社<img src="../../../assets2/img/CG2-pageFooter/pxg-logo.svg" alt="Pixel Grid" width="128" height="32"></div>
    </div>
  </div>
<!-- /.CG2-pageFooter --></footer>
```

**Comment by yomotsu** [comment]
@ykhs 
追加しておきました
http://ui.codegrid.net/styleguide/category/Templates/index.html#Page Footer

**Comment by ykhs** [comment]
@yomotsu 

ありがとうございます。反映しましたー。
https://dev-codegrid-pr-416.herokuapp.com/payment

![local codegrid 2015-12-10 18-50-09](https://cloud.githubusercontent.com/assets/203110/11712250/127c685e-9f6f-11e5-8a14-5cb4840c0b20.png)
