### ISSUE TITLE
filter: blur(24px) がすこぶる重いような

### ISSUE THREAD

**Issue by leader22** [pxgrid/codegrid-ui#29]
シリーズ一覧など、背景画像を`blur`で表示してるところ全般。

- スイーッと速めにスクロールすると、描画が追いつかずにそれはもうこの上なくチラつく。
- FireFoxとかだとよりひどかった・・。
- `will-change`とかあてると多少マシだがあくまで多少・・

**Comment by ykhs** [comment]
@yomotsu 

画像加工はLambdaの方でやってもらうようにして作業手順もまとめておいたので、`filter: blur(24px)`は切ってしまって大丈夫です。

**Comment by yomotsu** [comment]
CSS側で

.CG2-seriesList__coverImage
.CG2-seriesHeader__bg
.CG2-articleHeader__bg

**Comment by yomotsu** [comment]
完了close
