### ISSUE TITLE
Node を 4にする

### ISSUE THREAD

**Issue by yomotsu** [pxgrid/codegrid-ui#31]

**Comment by yomotsu** [comment]
done

**Comment by kyosuke** [comment]
これ、circle.ymlも修正しました？

**Comment by yomotsu** [comment]
https://github.com/pxgrid/codegrid-ui/commit/31e0453c73696b774b0f6440fdcd9a7ede6c97d3

忘れていました
4.2.2にしました

**Comment by kyosuke** [comment]
LGTM
