### ISSUE TITLE
シェア導線をひらくjsでエラー

### ISSUE THREAD

**Issue by leader22** [pxgrid/codegrid-ui#34]
HTMLはなくなったけどjsが残っててエラーになってるぽい。
これは既知のやつですか？

いちおう確認するなら・・

- 本番でどの記事でもいいのでひらく
- `Uncaught TypeError: Cannot read property 'addEventListener' of null`

<img width="421" alt="2015-12-18 21 30 38" src="https://cloud.githubusercontent.com/assets/6259812/11896977/b15c3d54-a5ce-11e5-8fd2-dd55c24a2a0c.png">

**Comment by kyosuke** [comment]
気づいてなかった気がする！

@ykhs appでなおせるとこ？

**Comment by leader22** [comment]
- cg-ui側のgulpのビルドから当該コードをはずす
- もっかいビルドする
- それをpublish
- app側でupdate

が必要かとー

**Comment by kyosuke** [comment]
@yomotsu じゃ、uiあっぷでーとよろ。

**Comment by yomotsu** [comment]
@kyosuke @leader22 いまって、ソーシャル系ボタンてボタン押したタイミングでJSで展開するのやめたんでしたっけ？

**Comment by geckotang** [comment]
@yomotsu https://github.com/pxgrid/codegrid-app/issues/486 の件で、テンプレートタグがJSの中にあると展開されないので、開閉機能を取っ払って直接Jadeにボタンを記述してます。

**Comment by leader22** [comment]
めも: この処理も無駄なのであわせて消したい

https://github.com/pxgrid/codegrid-app/blob/master/views/app/src/js/controller/entry.js#L9-L15

**Comment by leader22** [comment]
修正されてたので〆
