### ISSUE TITLE
ウィンドウ幅中くらいでメニューが落ちてブチ切れる

### ISSUE THREAD

**Issue by Takazudo** [pxgrid/codegrid-ui#39]
@yomotsu 

なんかこんな風になってた

<img width="897" alt="2016-01-21 17 08 57" src="https://cloud.githubusercontent.com/assets/128233/12474922/4ba6b774-c062-11e5-8c9c-13f0e0cc6296.png">

**Comment by yomotsu** [comment]
あー、この前text-overflowの調整した時にa要素のmax-widthを決め打ちして、それを解除するのを忘れていました。

下におちるのは、画面幅が足りないので意図してです。

**Comment by yomotsu** [comment]
https://github.com/pxgrid/codegrid-ui/commit/b0c8bd76562a7e7575861b58eace4f12ec498528
