### ISSUE TITLE
コードブロックの1行目の開始位置がずれる

### ISSUE THREAD

**Issue by nakajmg** [pxgrid/codegrid-ui#43]
![image](https://cloud.githubusercontent.com/assets/1995370/15304639/832cddf2-1bf9-11e6-88f6-996d04438068.png)

この`padding`の影響でファイル名がないコードブロックの場合に１行目の先頭位置がほかの行とずれている。

![pasted image at 2016_05_17 06_26](https://cloud.githubusercontent.com/assets/1995370/15304627/6aa6df62-1bf9-11e6-979f-b2447fa7ab70.png)

![image](https://cloud.githubusercontent.com/assets/1995370/15304617/58e720ac-1bf9-11e6-81cb-011bad5158d7.png)

**Comment by yomotsu** [comment]
ご指摘ありがとうございます。
codegrid-ui@1.1.5 が取り込まれたら解決しそうです。

**Comment by leader22** [comment]
取り込み済み + 現状で問題ないので〆

**Comment by yomotsu** [comment]
🙇
