### ISSUE TITLE
transparentButtton用の、disabledモディファイアがない

### ISSUE THREAD

**Issue by yomotsu** [pxgrid/codegrid-ui#46]
transparentButtton用の、disabledモディファイアを用意する

![pasted_image_at_2016_07_09_02_42](https://cloud.githubusercontent.com/assets/212837/16696316/4ccc1606-457f-11e6-98e4-81d0600fbcd0.png)

**Comment by yomotsu** [comment]
実はあった。
https://github.com/pxgrid/codegrid-ui/blob/master/src/assets2/scss/_components.scss#L234

指定方法が間違っているみたい。

**Comment by geckotang** [comment]
https://github.com/pxgrid/codegrid-app/blob/cf3fb0266f0b880e0e2b6e75fb5393b56513a390/views/app/src/js/component/toggleFavSeries.js#L20

codegrid-app側でmodifier切り替えてる
