### ISSUE TITLE
ヘッダの検索ボックスのホバー時がちょっとおかしい

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#54]
下のボーダーが隠れちゃってます。

![screen shot 2016-11-22 at 17 22 58](https://cloud.githubusercontent.com/assets/413984/20516198/aba47bcc-b0d8-11e6-859f-f33d20b38abc.png)

ヘッダちょっと変えたときの副作用でしょうか。

https://github.com/pxgrid/codegrid-ui/blob/master/src/assets2/scss/_template.scss#L388 で上下のpaddingを3pxとかに減らしたら、いちおうよろしくなりました。

**Comment by yomotsu** [comment]
ほんとだ！ご指摘ありがとうございます。
とりあえず自分アサインしておきます

**Comment by myakura** [comment]
前提：
* `.CG2-pageHeader__search`の高さが32px固定
* 1pxのボーダーがついてbox-sizing: border-boxなので中の高さが30pxでないといけない

みてみた：
* inputのline-heightがnormalになっている（normalize.css由来）
  * のでブラウザのデフォルトスタイルによって高さが違う
    * 手元のChromeだと24px, Firefoxだと25px
* 上下に4pxのpaddingがついて、かつbox-sizing: border-boxなので、22pxに固定じゃないといけない

というわけでinputだけline-heightを22pxに固定するのがよさそう。
