### ISSUE TITLE
LFとCRLFなファイルが混在している

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#57]
現状`.editorconfig`などもないため、ファイル内で混在することも起こりそうでなんか気持ち悪いので、どちらか（たぶんLF）に変換するのはどうでしょう。

**Comment by kyosuke** [comment]
統一した上で `.editorconfig` を足したら良さそうですね。

**Comment by yomotsu** [comment]
mergeしたのでcloseします
