### ISSUE TITLE
コードブロックのマージンが変

### ISSUE THREAD

**Issue by Takazudo** [pxgrid/codegrid-ui#59]
下が詰まっている（かコラムの上が詰まってる？）みたいです〜

---

<img width="669" alt="2016-12-15 11 12 30" src="https://cloud.githubusercontent.com/assets/128233/21209435/91e4e000-c2b7-11e6-8871-3271e7277470.png">

**Comment by myakura** [comment]
コラムにはマージンがなくて、コードブロックは上下0.5emだけなので詰まってるみたいですね。
（pは2em）

`コードブロック + コラム { margin-top: 2em }`とかやればいいんですかねえ。だいぶ場当たりではありますが…
