### ISSUE TITLE
アプリ内通知領域バーのUIを追加

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#73]
https://github.com/pxgrid/codegrid-app/issues/804 にて、iOSで購読してない人向けにメッセージを表示するバーを導入したいというお話なので、UIに追加したい。

![image](https://cloud.githubusercontent.com/assets/413984/24324161/9154b690-11c4-11e7-87d9-e6d323d5b637.png)

加えて、新しい団体購読の画面でも、色などは違うが役割は似てそうなパーツが求められている。

![image](https://cloud.githubusercontent.com/assets/413984/24324208/72336468-11c5-11e7-9c74-dc8000915c6b.png)

というわけで、「アプリ内通知領域」という感じの役割を持つUIを追加する。

**Comment by myakura** [comment]
バー、[articleNoticeなるもの](https://github.com/pxgrid/codegrid-ui/blob/ab644e861e679e841e0b86cb8874ff34ca0a5d21/src/assets2/scss/_components.scss#L2797-L2867)のスタイルを拝借すれば背景やらアイコン周りはよさそう。
articleNoticeを拡張するのも考えたけど、ちょっとスタイルが違うのと、記事についてのnoticeっぽいので性質が違うという…設計ってむつかしいね。

ボタンは[transparentButton](https://github.com/pxgrid/codegrid-ui/blob/ab644e861e679e841e0b86cb8874ff34ca0a5d21/src/assets2/scss/_components.scss#L212-L318)が使えるかもしれないが、文字サイズが小さいかもしれない。

**Comment by myakura** [comment]
そういえば、新しい団体購読の画面でも、ちょいと違うがバーがでるのだった。
![image](https://cloud.githubusercontent.com/assets/413984/24324183/e9cf2576-11c4-11e7-96df-afee735fa8f3.png)

なので、articleNoticeのスタイルを抽象クラスにして、iOS用、団体購読用、articleNoticeで継承させるように書き換えればいいのかな。

というかiOS用、団体購読用じゃなくて、アプリ内通知領域という感じに名前づけすれば汎用性高まるか。

**Comment by yomotsu** [comment]
`articleNotice`とは別の進化をする可能性があるので、完全に別で新規につくってしまってもいいかもしれませんね

**Comment by myakura** [comment]
PR放置してた…追加した。
あとはcodegrid-appのテンプレート修正を。
