### ISSUE TITLE
フッタのカテゴリ一覧が整列していない

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#80]
![screen shot 2017-04-03 at 13 21 13](https://cloud.githubusercontent.com/assets/413984/24598231/44792334-1885-11e7-90f6-a559d25e4960.png)

なんかいじって消してしまったかもしれんなあ…うええ。

**Comment by geckotang** [comment]
@myakura Chrome 57からっぽい？ columnがちゃんと実装されたのかな。

**Comment by myakura** [comment]
あーなるほど、マルチカラムのやつでli:first-childのmarginがcollapseしないというあれですか。
Firefox 55でも同様になってた（おそらく52でunprefixされたのでそれくらいからか）ので、めんどいですなー
flexboxあたりにすればいいかしら…

**Comment by geckotang** [comment]
gridという手も

**Comment by myakura** [comment]
https://github.com/pxgrid/codegrid-ui/commit/5868b5df9c733cb0169101076aa624fec114ae20 でとりあえずの修正
