### ISSUE TITLE
www用のスタイルを分離する

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-ui#90]
codegrid-ui.cssはwww用、app用のスタイルがいっしょくたになっているので無駄が多い。
SassとGulpつかってるので、出し分けるようなコードを書く。

出力するファイルとその組み合わせ方はいまの構成把握してからもっかい考える。

**Comment by kyosuke** [comment]
@myakura サイト単位でわけるのではなく、必要なものだけを読み込ませることが可能なようにコンポーネントというかカテゴリというかそういう単位で分けるのはどうでしょう？

codegrid-ui.css （全部入り）
codegrid-ui-base.css （どのページでも使うような必須スタイルだけ）
codegrid-ui-forms.css （フォームに関係するやつだけ）
codegrid-ui-wwwtop.css （wwwのトップでつかうやつだけ）
...

wwwのほうはhttp2対応なので、多少リクエスト数が増えても大丈夫なはずで、ページごとに必要なものだけ読むようにするとより無駄なくできるのかなと思いました。

あとcodegrid-ui単体としても全部入り、または個別に読み込みという単位のほうが綺麗かな？

**Comment by myakura** [comment]
> サイト単位でわけるのではなく、必要なものだけを読み込ませることが可能なようにコンポーネントというかカテゴリというかそういう単位で分けるのはどうでしょう？

あ、それはもうちょっと大きな計画ではあったのですよね。
いまのcodegrid-uiのコンポーネント的なものは [_components.scss](https://github.com/pxgrid/codegrid-ui/blob/master/src/assets2/scss/_components.scss) と [_www.scss](https://github.com/pxgrid/codegrid-ui/blob/master/src/assets2/scss/_www.scss) という2つに大きく分かれているので、まずはこの2つを分けられたらなと思ってました。

> wwwのほうはhttp2対応なので、多少リクエスト数が増えても大丈夫なはずで、ページごとに必要なものだけ読むようにするとより無駄なくできるのかなと思いました。

おっしゃるとおりです。なのでなおさら分離しやすいwwwからという意図です。

ただ、[コンポーネント以外はそれなりに分かれている](https://github.com/pxgrid/codegrid-ui/tree/master/src/assets2/scss)ので、base＋www（など）のような構成に踏み込んでもいいかもしれませんねー

**Comment by kyosuke** [comment]
はーい。実際の状況みていい感じにしてもらえれば問題ありませんので基本はお任せします。

**Comment by myakura** [comment]
1.7.1でとりあえず分離の初期段階は終了したのでこちらはクローズ。
もうちょい細かくするのはまたissueたてる。
